#  _____ _                             ___             __ _                             
# /__   \ |__   ___ _ __ ___   ___    / __\___  _ __  / _(_) __ _ 
#   / /\/ '_ \ / _ \ '_ ` _ \ / _ \  / /  / _ \| '_ \| |_| |/ _` |
#  / /  | | | |  __/ | | | | |  __/ / /__| (_) | | | |  _| | (_| |
#  \/   |_| |_|\___|_| |_| |_|\___| \____/\___/|_| |_|_| |_|\__, |
#                                                           |___/                                   
# MaterializeCSS Theme for Hexo - Created by Unixfy (https://github.com/unixfy)
# MIT License

favicon: 
  default: img/favicon.png

poweredby: true

author:
  firstname: Alex
  lastname: Wang
  alias: Unixfy
  fullname: Alex Wang
  github: https://github.com/unixfy

about:
  title1: Who am I?
  title2: Where's my Work?
  title3: Where's my Contact Info?
  desc1: I am a developer who creates apps and interfaces for clients (and myself). I like to use frameworks like Bootstrap or Materialize.css (my two favorite) to build these.
  desc2: You can find all of my personal projects and contributions to other OS projects on my <a class="yellow-text" href="<%= url_for(theme.author.github) %>" target="_blank">GitHub <i aria-hidden="true" class="fa fa-external-link"></i></a>, though I do maintain a few private projects.
  desc3: Feel free to contact me via email at <a class="tooltipped yellow-text" data-delay="50" data-position="left" data-tooltip="Click to Reveal Address" href="<%= url_for(theme.contact.email) %>" target="_blank">@unixfy.me</a>.

contact:
  email: https://spamty.eu/mail/v4/557/G39TCD287Gb799ba7c/

donate:
  paypal: https://paypal.me/unixfy
  cryptos: https://www.cryptonator.com/api/merchant/v1/startpayment?merchant_id=499a9efd3dc7caa64c8a9416bbe48fff&item_name=Donation&invoice_amount=1&invoice_currency=usd&language=en&item_description=Thanks+for+donating+%3A%29&order_id=DON-1