#  _____ _                             ___             __ _
# /__   \ |__   ___ _ __ ___   ___    / __\___  _ __  / _(_) __ _
#   / /\/ '_ \ / _ \ '_ ` _ \ / _ \  / /  / _ \| '_ \| |_| |/ _` |
#  / /  | | | |  __/ | | | | |  __/ / /__| (_) | | | |  _| | (_| |
#  \/   |_| |_|\___|_| |_| |_|\___| \____/\___/|_| |_|_| |_|\__, |
#                                                           |___/
# MaterializeCSS Theme for Hexo - Created by Unixfy (https://github.com/unixfy)
# MIT License

favicon:
  default: img/favicon.png

poweredby: true

# Google Analytics needs to be MANAULLY configured with your tag code in _partial/analytics.ejs!
googleanalytics: true

author:
  firstname: Alex
  lastname: Wang
  alias: Unixfy
  fullname: Alex Wang
  github: https://github.com/unixfy

about:
  title1: Who am I?
  title2: Where's my Work?
  title3: Where's my Contact Info?

contact:
  email: https://spamty.eu/mail/v4/557/G39TCD287Gb799ba7c/

donate:
  paypal: https://paypal.me/unixfy
  cryptos: https://www.cryptonator.com/api/merchant/v1/startpayment?merchant_id=499a9efd3dc7caa64c8a9416bbe48fff&item_name=Donation&invoice_amount=1&invoice_currency=usd&language=en&item_description=Thanks+for+donating+%3A%29&order_id=DON-1

menu:
  Home: /
  Blog: /blog
  Portfolio: /portfolio
