#  _____ _                             ___             __ _                             
# /__   \ |__   ___ _ __ ___   ___    / __\___  _ __  / _(_) __ _ 
#   / /\/ '_ \ / _ \ '_ ` _ \ / _ \  / /  / _ \| '_ \| |_| |/ _` |
#  / /  | | | |  __/ | | | | |  __/ / /__| (_) | | | |  _| | (_| |
#  \/   |_| |_|\___|_| |_| |_|\___| \____/\___/|_| |_|_| |_|\__, |
#                                                           |___/                                   
# MaterializeCSS Theme for Hexo - Created by Unixfy (https://github.com/unixfy)
# MIT License

favicon: 
  default: img/favicon.png

poweredby: true

author:
  firstname: Alex
  lastname: Wang
  alias: Unixfy
  fullname: Alex Wang