version: 2
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:6.10"
    steps: 
      - checkout
      - 
        run: 
          command: "sudo npm install -g hexo-cli"
          name: "Install HexoCLI"
      - run:
          command: "sudo rm -rf node_modules/ && sudo npm install"
          name: "Reinstall Nodemodules"
      - 
        run: 
          command: "hexo clean"
          name: "Clean up Hexo"
      - run:
          command: "hexo generate"
          name: "Generate files Hexo"
      - run:
          command: "ssh-keyscan -H unixfy.me >> ~/.ssh/known_hosts"
          name: "Add server SSH key"
      - 
        run: 
          command: "scp -r public/ ubuntu@unixfy.me:/var/www/unixfy"
          name: "Deploy to server!"


