version: 2
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:6.10"
    steps: 
      - checkout
      - 
        run: 
          command: "sudo npm install -g hexo-cli"
          name: "Install HexoCLI"
      - run:
          command: "sudo rm -rf node_modules/ && sudo npm install"
          name: "Reinstall Nodemodules"
      - 
        run: 
          command: "git config --global user.name 'Unixfy via CircleCI' && git config --global user.email 'admin@x2c0.net'"
          name: "Setup Git"
      - 
        run: 
          command: "hexo clean"
          name: "Clean up Hexo"
      - run:
          command: "hexo generate"
          name: "Generate files Hexo"
      - 
        run: 
          command: "cp appspec.yml public/appspec.yml"
          name: "Copy AppSpec.yml"
      - 
        run: 
          command: "hexo deploy"
          name: "Deploy to AWS CodeStar!"


