version: 2
jobs:
  build:
    docker:
      - image:     "circleci/node:6.10"
    steps:
      - checkout
      - run:
          command: "sudo npm install -g hexo-cli"
          name:    "Install Hexo CLI globally to prepare for build"
      - run:
          command: "sudo rm -rf node_modules/ && sudo npm install"
          name:    "Remove node_modules and reinstall so everything installs correctly"
      - run:
          command: "hexo clean"
          name:    "Clean up Hexo"
      - run:
          command: "hexo generate"
          name:    "Tell Hexo to generate HTML files"
      - run:
          command: "hexo deploy"
          name:    "Deploy to S3 with credentials defined in CircleCI settings!"
