version: 2
jobs:
  build:
    docker:
      - image:     "circleci/python:latest-node"
    steps:
      - checkout
      - run:
          command: "sudo npm install -g hexo-cli"
          name:    "Install Hexo CLI globally to prepare for build"
      - run:
          command: "sudo rm -rf node_modules/ && sudo npm install --unsafe-perm=true --allow-root"
          name:    "Remove node_modules and reinstall so everything installs correctly"
      - run:
          command: "hexo clean"
          name:    "Clean up Hexo"
      - run:
          command: "hexo generate"
          name:    "Tell Hexo to generate HTML files"
      - run:
          command: "hexo deploy"
          name:    "Deploy to S3 with credentials defined in CircleCI settings!"
      - run:
          command: "sudo pip install awscli"
          name:    "Install the AWS CLI through python-pip"
      - run:
          command: aws cloudfront create-invalidation --distribution-id ESFJZLIOTD4Z  --paths "/*"
          name:    "Create AWS CloudFront invalidation so changes take effect immediately"
